# Generated by Django 3.2.9 on 2022-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='books_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
